/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TempoTrainerImport } from './routes/tempo-trainer'
import { Route as TempoTapperImport } from './routes/tempo-tapper'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TempoTrainerRoute = TempoTrainerImport.update({
  id: '/tempo-trainer',
  path: '/tempo-trainer',
  getParentRoute: () => rootRoute,
} as any)

const TempoTapperRoute = TempoTapperImport.update({
  id: '/tempo-tapper',
  path: '/tempo-tapper',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tempo-tapper': {
      id: '/tempo-tapper'
      path: '/tempo-tapper'
      fullPath: '/tempo-tapper'
      preLoaderRoute: typeof TempoTapperImport
      parentRoute: typeof rootRoute
    }
    '/tempo-trainer': {
      id: '/tempo-trainer'
      path: '/tempo-trainer'
      fullPath: '/tempo-trainer'
      preLoaderRoute: typeof TempoTrainerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tempo-tapper': typeof TempoTapperRoute
  '/tempo-trainer': typeof TempoTrainerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tempo-tapper': typeof TempoTapperRoute
  '/tempo-trainer': typeof TempoTrainerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tempo-tapper': typeof TempoTapperRoute
  '/tempo-trainer': typeof TempoTrainerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tempo-tapper' | '/tempo-trainer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tempo-tapper' | '/tempo-trainer'
  id: '__root__' | '/' | '/tempo-tapper' | '/tempo-trainer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TempoTapperRoute: typeof TempoTapperRoute
  TempoTrainerRoute: typeof TempoTrainerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TempoTapperRoute: TempoTapperRoute,
  TempoTrainerRoute: TempoTrainerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tempo-tapper",
        "/tempo-trainer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tempo-tapper": {
      "filePath": "tempo-tapper.tsx"
    },
    "/tempo-trainer": {
      "filePath": "tempo-trainer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
