name: Deploy to Hosting

on:
  push:
    branches:
      - dev # You can adjust this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Install dependencies
        run: |
          cd astro
          npm install

      - name: Build project
        run: | 
          cd astro
          npm run build

      - name: Test SSH connectivity
        run: |
          ssh -v -o StrictHostKeyChecking=no -p 7822 elliotre@elliotreed.net "echo 'SSH connection successful'"

      - name: Ensure target directory exists
        run: ssh -p 7822 elliotre@elliotreed.net "mkdir -p /home/elliotre/staging.metronome.elliotreed.net/"

      - name: Deploy via rsync
        run: |
          rsync -avz --delete --exclude '.well-known' --exclude 'cgi-bin' -e "ssh -p 7822" ./dist/ elliotre@elliotreed.net:/home/elliotre/staging.metronome.elliotreed.net/
